import {createClient} from '@supabase/supabase-js';
import {config} from './config.js';
export const configured=Boolean(config.supabaseUrl&&config.supabasePublishableKey);
export const supabase=configured?createClient(config.supabaseUrl,config.supabasePublishableKey):null;
export async function loadRemote(){let {data,error}=await supabase.from('crm_workspaces').select('payload,revision').maybeSingle();if(error)throw error;return data;}
export async function saveRemote(payload,revision){let {data,error}=await supabase.rpc('save_crm_workspace',{p_payload:payload,p_revision:revision});if(error)throw error;return data;}
export async function putRemoteFile(file){if(file.size>10*1024*1024)throw Error('El límite por archivo es 10 MB.');let {data:{user}}=await supabase.auth.getUser();if(!user)throw Error('Inicia sesión de nuevo.');let id=crypto.randomUUID(),path=user.id+'/'+id;let {error}=await supabase.storage.from('crm-documents').upload(path,file,{contentType:'application/octet-stream',upsert:false});if(error)throw error;return {id,path,name:file.name,size:file.size,type:file.type,remote:true};}
export async function getRemoteFile(file){const {data,error}=await supabase.storage.from('crm-documents').download(file.path);if(error)throw error;return new File([data],file.name,{type:'application/octet-stream'});}
const openFiles=()=>new Promise((resolve,reject)=>{const request=indexedDB.open('orquivia-files-v2',1);request.onupgradeneeded=()=>request.result.createObjectStore('files');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});
export async function putFile(file){if(file.size>10*1024*1024)throw Error('El límite por archivo es 10 MB.');let db=await openFiles(),id=crypto.randomUUID();await new Promise((resolve,reject)=>{let tx=db.transaction('files','readwrite');tx.objectStore('files').put(file,id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close();return {id,name:file.name,size:file.size,type:file.type};}
export async function getFile(id){let db=await openFiles();let value=await new Promise((resolve,reject)=>{let r=db.transaction('files').objectStore('files').get(id);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});db.close();return value;}
