import {ensureTeam} from './team-model.js';
export const schedules = {start:'Al inicio',milestone:'Por hitos',end:'Al finalizar',monthly:'Mensual'};
export const requestStates = {pending:'Por revisar',preparing:'En preparación',done:'Documento preparado',cancelled:'Cancelada'};
export const today=()=>new Date().toISOString().slice(0,10);
const id=()=>crypto.randomUUID();
const round=n=>Math.round((n+Number.EPSILON)*100)/100;
export function ensureBilling(data){
  data.billing??={settings:{company:'',taxId:'',address:'',email:'',iban:'',prefixQuote:'PRE',prefixInvoice:'FAC',nextQuote:1,nextInvoice:1,tax:21,days:30,schedule:'end',terms:'Transferencia bancaria'},projects:{},requests:[],documents:[],payments:[]};
  data.billing.customers??=[];data.billing.catalog??=[];
  data.billing.templates??=[{id:'certificate',name:'Certificación por estructura',body:'Proyecto: {{proyecto}}\nEstructura / ubicación: {{unidad}}\nServicio: {{trabajo}}\nCliente: {{cliente}}\nFecha: {{fecha}}\nResponsable: {{responsable}}\n\nDocumentación revisada: {{observaciones}}\n\nResultado y condiciones de la revisión: completar antes de emitir.'}];
  data.billing.deliverables??=[];
  for(const d of data.deals)data.billing.projects[d.id]??={code:'',schedule:data.billing.settings.schedule,customer:d.values.company||d.values.contact||'',taxId:'',address:'',email:d.values.email||'',owner:'',nextDate:'',note:'',works:[]};
  for(const p of Object.values(data.billing.projects)){if(!p.customerId&&p.customer&&p.taxId&&p.address){let c=data.billing.customers.find(c=>c.taxId.toLowerCase()===p.taxId.toLowerCase());if(!c){c={id:id(),name:p.customer,taxId:p.taxId,address:p.address,email:p.email||'',contact:''};data.billing.customers.push(c);}p.customerId=c.id;}}
  return data.billing;
}
export function amounts(lines){const base=round(lines.reduce((s,l)=>s+round(Number(l.qty)*Number(l.price)*(1-Number(l.discount||0)/100)),0));const tax=round(lines.reduce((s,l)=>s+round(round(Number(l.qty)*Number(l.price)*(1-Number(l.discount||0)/100))*Number(l.tax)/100),0));return {base,tax,total:round(base+tax)};}
export function paid(b,doc){return round(b.payments.filter(p=>p.document===doc.id).reduce((n,p)=>n+p.amount,0));}
export function balance(b,doc){return round(Math.max(0,doc.total-paid(b,doc)));}
export function documentState(b,doc){if(doc.status==='void')return 'Anulado';if(doc.type==='quote')return doc.accepted?'Aceptado por cliente':({draft:'Borrador',review:'Pendiente de revisión',approved:'Aprobado'}[doc.status]||'Preparado');if(balance(b,doc)===0)return 'Cobrado';if(doc.due<today())return 'Vencido';return paid(b,doc)>0?'Cobro parcial':'Pendiente de cobro';}
export function addWork(data,deal,v){const b=ensureBilling(data),p=b.projects[deal];if(!p)throw Error('Proyecto no encontrado.');const w={id:id(),label:v.label.trim(),qty:Number(v.qty),price:Number(v.price),tax:Number(v.tax),discount:Number(v.discount||0),productId:v.productId||'',code:v.code||'',category:v.category||'',unit:v.unit||'servicio',taxKind:v.taxKind||'vat',taxReason:v.taxReason||'',customerId:v.customerId||p.customerId||'',entity:v.entity||'',managed:!!v.managed,execution:'pending',commercial:v.commercial||'quote',agreement:v.agreement||'',history:[],createdAt:new Date().toISOString()};if(!w.label||!Number.isFinite(w.qty)||w.qty<=0||!Number.isFinite(w.price)||w.price<0||!Number.isFinite(w.tax)||w.tax<0||w.tax>100||!Number.isFinite(w.discount)||w.discount<0||w.discount>100)throw Error('Revisa el concepto, la cantidad, el precio y el impuesto.');p.works.push(w);return w;}
export function requestDocument(data,deal,v,workIds){const b=ensureBilling(data),p=b.projects[deal],d=data.deals.find(d=>d.id===deal);if(!p||!d)throw Error('Proyecto no encontrado.');if(!['quote','invoice'].includes(v.type))throw Error('Tipo de documento no válido.');let lines=p.works.filter(w=>workIds.includes(w.id));if(!lines.length)throw Error('Selecciona al menos un trabajo.');if(p.schedule==='monthly'&&!/^\d{4}-(0[1-9]|1[0-2])$/.test(v.period||''))throw Error('Indica el mes que se va a facturar.');const period=p.schedule==='monthly'?v.period:'';
  const payerIds=[...new Set(lines.map(w=>w.customerId||p.customerId||''))];if(payerIds.length>1)throw Error('Selecciona trabajos de un mismo cliente fiscal. Genera documentos separados para cada empresa.');
  const customerId=v.customerId||payerIds[0];if(payerIds[0]&&v.customerId&&payerIds[0]!==v.customerId)throw Error('El cliente elegido no coincide con el pagador de estos trabajos.');
  const customer=b.customers.find(c=>c.id===customerId);if(customerId&&!customer)throw Error('Cliente fiscal no encontrado.');
  if(v.type==='invoice')for(const w of lines.filter(w=>w.managed)){const accepted=b.documents.some(doc=>doc.type==='quote'&&doc.accepted&&doc.deal===deal&&doc.period===period&&doc.lines.some(l=>l.id===w.id));if(w.commercial!=='agreement'&&!accepted)throw Error('Registra la aceptación del presupuesto o un acuerdo previo para «'+w.label+'».');if(w.commercial==='agreement'&&!w.agreement?.trim())throw Error('Indica la referencia del acuerdo previo.');if(w.execution!=='done'&&!v.advance)throw Error('Confirma la ejecución de «'+w.label+'» o solicita un anticipo con motivo.');}
  if(v.advance&&!v.note?.trim())throw Error('Indica el motivo del cobro anticipado.');
  if(v.type==='invoice')lines=lines.map(w=>{const quote=b.documents.find(d=>d.type==='quote'&&d.accepted&&d.deal===deal&&d.period===period&&d.lines.some(l=>l.id===w.id));return quote?{...w,...structuredClone(quote.lines.find(l=>l.id===w.id))}:w;});
  const duplicate=b.requests.some(r=>r.deal===deal&&r.type===v.type&&r.period===period&&r.status!=='cancelled'&&r.lines.some(l=>lines.some(w=>w.id===l.id)));
  if(duplicate)throw Error('Algún trabajo ya tiene una solicitud de este tipo para ese período. Revisa la bandeja antes de duplicarlo.');
  const team=ensureTeam(data);if(v.assignee&&!team.members.some(m=>m.id===v.assignee))throw Error('El destinatario debe pertenecer a la empresa.');const r={id:id(),customerId,customer:structuredClone(customer||{name:p.customer,taxId:p.taxId,address:p.address,email:p.email}),code:p.code,paymentDays:Number(v.paymentDays??p.paymentDays??b.settings.days),paymentMethod:v.paymentMethod||p.paymentMethod||b.settings.terms,advance:!!v.advance,assignee:v.assignee||team.currentUser,createdBy:team.currentUser,deal,title:d.values.title,type:v.type,period,needed:v.needed||today(),note:v.note||'',by:data.settings.name,at:new Date().toISOString(),status:'pending',lines:structuredClone(lines),history:[]};b.requests.unshift(r);return r;
}
export function prepareDocument(data,requestId,v){const b=ensureBilling(data),r=b.requests.find(r=>r.id===requestId);if(!r||!['pending','preparing'].includes(r.status))throw Error('Esta solicitud ya se ha tramitado.');const p=b.projects[r.deal],s=b.settings;if(!s.company||!s.taxId||!s.address)throw Error('Completa los datos del emisor en Reglas y datos.');const client=(r.customerId||r.customer?.taxId&&r.customer?.address?r.customer:null)||{name:p.customer,taxId:p.taxId,address:p.address,email:p.email};if(!client.name||!client.taxId||!client.address||!(r.code||p.code))throw Error('Completa cliente, identificación fiscal, dirección y código de facturación del proyecto.');if(!v.date||!v.due||v.due<v.date)throw Error('Revisa las fechas del documento y del vencimiento.');const invoice=r.type==='invoice',counter=invoice?'nextInvoice':'nextQuote',prefix=invoice?s.prefixInvoice:s.prefixQuote;const number=`${prefix}-${v.date.slice(0,4)}-${String(s[counter]).padStart(4,'0')}`;if(b.documents.some(d=>d.number===number))throw Error('La numeración ya existe. Revisa el siguiente número en las reglas.');const doc={id:id(),request:r.id,deal:r.deal,type:r.type,number,date:v.date,due:v.due,title:r.title,code:r.code||p.code,period:r.period,paymentDays:r.paymentDays??s.days,paymentMethod:r.paymentMethod||s.terms,customerId:r.customerId||'',issuer:structuredClone(s),customer:structuredClone(client),lines:structuredClone(r.lines),...amounts(r.lines),notes:v.notes||'',status:invoice?'prepared':'draft',preparedBy:v.preparedBy||data.settings.name,reviewer:v.reviewer||ensureTeam(data).members.find(m=>m.id===r.assignee)?.name||'',reviewerId:v.reviewerId||r.assignee||'',audit:[{at:new Date().toISOString(),text:'Preparado por '+(v.preparedBy||data.settings.name)}],accepted:false,files:[],createdAt:new Date().toISOString()};b.documents.unshift(doc);s[counter]++;r.status='done';r.history.push({at:new Date().toISOString(),text:`Documento ${number} preparado por ${data.settings.name}`});return doc;}
export function addPayment(data,documentId,v){const b=ensureBilling(data),d=b.documents.find(d=>d.id===documentId),amount=round(Number(v.amount));if(!d||d.type!=='invoice'||d.status==='void')throw Error('Selecciona una factura activa.');if(!Number.isFinite(amount)||amount<=0||amount>balance(b,d))throw Error('El cobro debe ser positivo y no superar el saldo pendiente.');if(!v.date)throw Error('Indica la fecha del cobro.');b.payments.unshift({id:id(),document:d.id,date:v.date,amount,method:v.method||'Transferencia',reference:v.reference||'',by:data.settings.name});}
export function projectSummary(data,deal){const b=ensureBilling(data),docs=b.documents.filter(d=>d.deal===deal&&d.type==='invoice'&&d.status!=='void');return {budget:amounts(b.projects[deal].works).total,invoiced:round(docs.reduce((n,d)=>n+d.total,0)),paid:round(docs.reduce((n,d)=>n+paid(b,d),0)),pending:round(docs.reduce((n,d)=>n+balance(b,d),0)),requests:b.requests.filter(r=>r.deal===deal&&['pending','preparing'].includes(r.status)).length};}
export function csv(rows){return '\ufeff'+rows.map(row=>row.map(value=>{let s=String(value??'');if(/^[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';}).join(';')).join('\r\n');}

export function quoteTransition(data,documentId,action){
 const b=ensureBilling(data),d=b.documents.find(d=>d.id===documentId);if(!d||d.type!=='quote')throw Error('Presupuesto no encontrado.');
 const next={review:['draft','review'],approve:['review','approved'],reopen:['review','draft'],accept:['approved','approved']};const rule=next[action];
 if(!rule||d.status!==rule[0])throw Error('El presupuesto no está en el estado necesario.');
 if(action==='review'&&!d.reviewer.trim())throw Error('Indica quién debe revisar el presupuesto.');
 d.status=rule[1];if(action==='accept')d.accepted=true;d.audit??=[];d.audit.unshift({at:new Date().toISOString(),text:({review:'Enviado a revisión de '+d.reviewer,approve:'Presupuesto aprobado',reopen:'Devuelto a borrador',accept:'Aceptación del cliente registrada'})[action]+' · '+data.settings.name});
}
export function editQuote(data,documentId,v,lines){const d=ensureBilling(data).documents.find(d=>d.id===documentId);if(!d||d.type!=='quote'||d.status!=='draft')throw Error('Solo se pueden editar presupuestos en borrador.');if(!v.preparedBy.trim())throw Error('Indica quién prepara el presupuesto.');if(!v.due||v.due<d.date)throw Error('Revisa la fecha de validez.');if(lines.some(l=>!l.label.trim()||!Number.isFinite(l.qty)||l.qty<=0||!Number.isFinite(l.price)||l.price<0||!Number.isFinite(l.tax)||l.tax<0||l.tax>100))throw Error('Revisa los importes de los trabajos.');Object.assign(d,{preparedBy:v.preparedBy,reviewer:v.reviewer,reviewerId:v.reviewerId||d.reviewerId||'',notes:v.notes,due:v.due,lines,...amounts(lines)});}
export function invoiceAcceptedQuote(data,documentId){const b=ensureBilling(data),d=b.documents.find(d=>d.id===documentId);if(!d||d.type!=='quote'||!d.accepted)throw Error('Registra primero la aceptación del cliente.');const r=requestDocument(data,d.deal,{type:'invoice',period:d.period,needed:today(),customerId:d.customerId,paymentDays:d.paymentDays,paymentMethod:d.paymentMethod,note:'Facturar presupuesto aceptado '+d.number},d.lines.map(l=>l.id));r.lines=structuredClone(d.lines);r.quote=d.id;r.customer=structuredClone(d.customer);return r;}

export function taxBreakdown(lines){const groups=new Map();for(const l of lines){const key=(l.taxKind||'vat')+':'+l.tax;const a=amounts([l]),g=groups.get(key)||{label:l.taxKind==='exempt'?'Exento':'IVA '+l.tax+'%',base:0,tax:0};g.base=round(g.base+a.base);g.tax=round(g.tax+a.tax);groups.set(key,g);}return [...groups.values()];}
export function saveCustomer(data,v){const b=ensureBilling(data);if(!v.name?.trim()||!v.taxId?.trim()||!v.address?.trim())throw Error('Completa nombre fiscal, identificación y dirección.');let row=b.customers.find(c=>c.id===v.id);const duplicate=b.customers.find(c=>c.taxId.toLowerCase()===v.taxId.trim().toLowerCase()&&c.id!==v.id);if(duplicate)throw Error('Ya existe un cliente con esa identificación fiscal.');if(!row){row={id:id()};b.customers.push(row);}Object.assign(row,{name:v.name.trim(),taxId:v.taxId.trim(),address:v.address.trim(),email:v.email||'',contact:v.contact||''});return row;}
export function saveProduct(data,v){const b=ensureBilling(data);if(!v.name?.trim()||!v.code?.trim())throw Error('Indica nombre y código del servicio.');let row=b.catalog.find(p=>p.id===v.id);if(b.catalog.some(p=>p.code.toLowerCase()===v.code.trim().toLowerCase()&&p.id!==v.id))throw Error('Ese código ya existe en el catálogo.');const price=Number(v.price),tax=Number(v.tax);if(!Number.isFinite(price)||price<0||!Number.isFinite(tax)||tax<0||tax>100)throw Error('Revisa precio e IVA.');if(!row){row={id:id()};b.catalog.push(row);}Object.assign(row,{name:v.name.trim(),code:v.code.trim(),price,tax,unit:v.unit||'servicio',category:v.category||'',taxKind:v.taxKind||'vat',taxReason:v.taxReason||''});return row;}

export function workStatus(data,deal,w){const b=ensureBilling(data),docs=b.documents.filter(d=>d.deal===deal&&d.type==='invoice'&&d.status!=='void'&&d.lines.some(l=>l.id===w.id));let invoiced=0,collected=0;for(const d of docs){const total=amounts(d.lines.filter(l=>l.id===w.id)).total;invoiced+=total;collected+=d.total?paid(b,d)*total/d.total:0;}return {invoiced:round(invoiced),collected:round(collected),pending:round(invoiced-collected),label:docs.length?(invoiced-collected<0.005?'Cobrado':collected?'Cobro parcial':'Pendiente de cobro'):b.requests.some(r=>r.deal===deal&&r.type==='invoice'&&r.status!=='cancelled'&&r.lines.some(l=>l.id===w.id))?'Solicitado':'Sin facturar'};}
export function completeWork(data,deal,workId){const w=ensureBilling(data).projects[deal].works.find(w=>w.id===workId);if(!w)throw Error('Trabajo no encontrado.');if(w.execution==='done')return;w.execution='done';w.completedAt=new Date().toISOString();w.completedBy=ensureTeam(data).currentUser;w.history??=[];w.history.unshift({at:w.completedAt,text:'Ejecución confirmada por '+data.settings.name});const d=data.deals.find(d=>d.id===deal);d.history.unshift({id:id(),at:w.completedAt,text:'Trabajo ejecutado: '+w.label+' · '+data.settings.name});}
export function renderTemplate(body,values){return body.replace(/\{\{(proyecto|unidad|trabajo|cliente|fecha|responsable|observaciones)\}\}/g,(_,k)=>values[k]||'');}
export function makeDeliverable(data,deal,workId,templateId){const b=ensureBilling(data),p=b.projects[deal],w=p.works.find(w=>w.id===workId),t=b.templates.find(t=>t.id===templateId),d=data.deals.find(d=>d.id===deal);if(!w||!t)throw Error('Selecciona un trabajo y una plantilla.');const c=b.customers.find(c=>c.id===(w.customerId||p.customerId));const doc={id:id(),deal,work:workId,title:t.name+' · '+(w.entity||w.label),body:renderTemplate(t.body,{proyecto:d.values.title,unidad:w.entity,trabajo:w.label,cliente:c?.name||p.customer,fecha:today(),responsable:data.settings.name,observaciones:''}),status:'draft',at:new Date().toISOString()};b.deliverables.unshift(doc);return doc;}
