import {ensureFlows,flowFor} from './workflows.js';
import {seed,stages,checklist} from './seed.js';
export {stages};
export const uid=()=>crypto.randomUUID();
export const folders=[['inbox','Bandeja de entrada'],['draft','Borradores'],['outbox','Bandeja de salida'],['sent','Enviados'],['archive','Archivo'],['trash','Papelera']];
export function settings(){return {name:'Nicole',workspace:'Mi espacio',font:'Arial',fontSize:'3',density:'comfortable',fields:[{id:'title',label:'Nombre del negocio',type:'text',required:true,builtin:true},{id:'contact',label:'Persona de contacto',type:'text',required:true,builtin:true},{id:'email',label:'Correo del contacto',type:'email',required:true,builtin:true},{id:'company',label:'Organización',type:'text',required:false,builtin:true},{id:'due',label:'Fecha objetivo',type:'date',required:false,builtin:true}],template:checklist.map(label=>({id:uid(),label})),labels:['Por revisar','Pendiente','Nuevo','Aprobado']}}
export function initial(demo=true,legacy){let cfg=settings(),source=demo?(legacy||structuredClone(seed)):{deals:[],mails:[],contacts:[]};const boxes=demo?[{id:'personal',label:'Nicole · Personal',email:'nicole@example.com',signature:'Nicole Pereyra\nCoordinación de proyectos\nOrquivia',kind:'demo'},{id:'team',label:'Equipo técnico',email:'equipo@example.com',signature:'Equipo técnico\nOrquivia',kind:'demo'}]:[];
return {schema:2,settings:cfg,mailboxes:boxes,contacts:source.contacts||[],deals:source.deals.map(d=>({...d,id:String(d.id),values:{title:d.title,contact:d.contact,email:d.email,company:d.company,due:''},items:cfg.template.map((t,i)=>({...t,done:!!d.checks[i]})),notes:[],history:[{id:uid(),at:new Date().toISOString(),text:'Negocio creado'}],files:[]})),mails:source.mails.map((m,i)=>({...m,id:String(m.id),deal:m.deal?String(m.deal):null,box:i%2?'team':'personal',cc:'',bcc:'',attachments:[],messages:[...(i===0?[{id:uid(),name:m.name,email:m.email,at:'16 sept · 09:15',text:'Buenos días, enviamos la primera propuesta para revisar los accesos.',attachments:[]},{id:uid(),name:'Nicole',email:'nicole@example.com',at:'17 sept · 11:30',text:'Gracias, Clara. Por favor, ajustad los accesos indicados antes de la validación final.',attachments:[]}]:[]),{id:uid(),name:m.name,email:m.email,at:m.time,text:m.body,attachments:[]}]}))};}
export function validateDeal(values,fields){for(const f of fields){let v=String(values[f.id]||'').trim();if(f.required&&!v)return `Completa «${f.label}».`;if(v&&f.type==='email'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v))return `Revisa «${f.label}».`;}return '';}
export function createDeal(data,values,mailId){let error=validateDeal(values,data.settings.fields);if(error)throw Error(error);ensureFlows(data);let d={id:uid(),values,flowId:data.settings.flows.some(f=>f.id===values.flowId)?values.flowId:data.settings.flows[0].id,stage:0,tag:'Documentación',items:data.settings.template.map(t=>({...t,done:false})),notes:[],files:[],history:[{id:uid(),at:new Date().toISOString(),text:'Negocio creado'}]};data.deals.push(d);if(mailId){let m=data.mails.find(m=>m.id===mailId);if(m)m.deal=d.id;}if(values.email&&!data.contacts.some(c=>c.email===values.email))data.contacts.push({id:uid(),name:values.contact,email:values.email,company:values.company});return d;}
export function counts(data){return {open:data.deals.filter(d=>flowFor(data,d).continuous||d.stage!==flowFor(data,d).stages.length-1).length,waiting:data.deals.filter(d=>flowFor(data,d).stages[d.stage]?.toLowerCase().includes('pendiente')).length,approved:data.deals.filter(d=>!flowFor(data,d).continuous&&d.stage===flowFor(data,d).stages.length-1).length,unlinked:data.mails.filter(m=>m.folder==='inbox'&&!m.deal).length,done:data.deals.reduce((n,d)=>n+d.items.filter(i=>i.done).length,0),total:data.deals.reduce((n,d)=>n+d.items.length,0)};}
export function visibleMails(data,{folder,box,query,filter}){return data.mails.filter(m=>m.folder===folder&&(box==='all'||m.box===box)&&(filter!=='unread'||m.unread)&&(filter!=='unlinked'||!m.deal)&&`${m.subject} ${m.name} ${m.email} ${m.tag}`.toLowerCase().includes(query.toLowerCase()));}
