import test from 'node:test';
import assert from 'node:assert/strict';
import {initial} from '../model.js';
import {ensureBilling,addWork,amounts,requestDocument,prepareDocument,addPayment,balance,paid,projectSummary,quoteTransition,editQuote,csv,invoiceAcceptedQuote,saveCustomer,saveProduct,taxBreakdown} from '../billing-model.js';
function setup(){let data=initial(true),b=ensureBilling(data),id=data.deals[0].id;Object.assign(b.settings,{company:'Emisor de prueba',taxId:'TEST-1',address:'Dirección de prueba'});Object.assign(b.projects[id],{code:'PR-001',customer:'Cliente de prueba',taxId:'TEST-2',address:'Dirección cliente'});let w=addWork(data,id,{label:'Revisión',qty:2,price:125,tax:21});return {data,b,id,w};}
test('billing migration preserves workspace and inherits defaults only on new projects',()=>{let {data,b,id}=setup();b.settings.schedule='monthly';ensureBilling(data);assert.equal(b.projects[id].schedule,'end');assert.equal(data.deals[0].values.title,'Foro Mediterráneo · Distribución');assert.equal(b.projects[id].works.length,1);});
test('multi-work request snapshots prices and rejects overlapping duplicate invoices',()=>{let {data,b,id,w}=setup();let w2=addWork(data,id,{label:'Plano',qty:1,price:100,tax:10});let r=requestDocument(data,id,{type:'invoice'},[w.id,w2.id]);assert.equal(amounts(r.lines).total,412.5);w.price=999;assert.equal(r.lines[0].price,125);assert.throws(()=>requestDocument(data,id,{type:'invoice'},[w2.id]),/ya tiene/);assert.equal(b.requests.length,1);});
test('monthly requests isolate periods and require a valid month',()=>{let {data,b,id,w}=setup();b.projects[id].schedule='monthly';assert.throws(()=>requestDocument(data,id,{type:'invoice',period:''},[w.id]),/mes/);requestDocument(data,id,{type:'invoice',period:'2026-09'},[w.id]);requestDocument(data,id,{type:'invoice',period:'2026-10'},[w.id]);assert.throws(()=>requestDocument(data,id,{type:'invoice',period:'2026-10'},[w.id]),/ya tiene/);});
test('partial payments reconcile balances and prevent overpayment',()=>{let {data,b,id,w}=setup(),r=requestDocument(data,id,{type:'invoice'},[w.id]),d=prepareDocument(data,r.id,{date:'2026-09-18',due:'2026-10-18'});addPayment(data,d.id,{amount:100,date:'2026-09-20'});assert.equal(balance(b,d),202.5);assert.equal(paid(b,d),100);assert.throws(()=>addPayment(data,d.id,{amount:203,date:'2026-09-20'}),/saldo/);addPayment(data,d.id,{amount:202.5,date:'2026-09-21'});assert.equal(projectSummary(data,id).pending,0);assert.throws(()=>prepareDocument(data,r.id,{date:'2026-09-18',due:'2026-10-18'}),/tramitado/);});
test('project owner can prepare editable quote with review and client acceptance',()=>{let {data,b,id,w}=setup(),r=requestDocument(data,id,{type:'quote'},[w.id]),d=prepareDocument(data,r.id,{date:'2026-09-18',due:'2026-10-18'});assert.equal(d.preparedBy,data.settings.name);assert.equal(d.status,'draft');assert.equal(d.reviewer,data.settings.name);editQuote(data,d.id,{preparedBy:'Responsable',reviewer:'Administración',notes:'Revisar',due:d.due},[{...d.lines[0],price:150}]);assert.equal(d.total,363);assert.equal(w.price,125);quoteTransition(data,d.id,'review');assert.throws(()=>editQuote(data,d.id,{},[]),/borrador/);quoteTransition(data,d.id,'approve');quoteTransition(data,d.id,'accept');assert.equal(d.accepted,true);assert.equal(projectSummary(data,id).invoiced,0);});
test('fiscal snapshots and sequential document identifiers stay stable',()=>{let {data,b,id,w}=setup(),r=requestDocument(data,id,{type:'invoice'},[w.id]),d=prepareDocument(data,r.id,{date:'2026-09-18',due:'2026-10-18'});b.settings.company='Changed';b.projects[id].code='Changed';assert.equal(d.issuer.company,'Emisor de prueba');assert.equal(d.code,'PR-001');assert.equal(d.number,'FAC-2026-0001');assert.equal(b.settings.nextInvoice,2);});
test('CSV neutralizes spreadsheet formulas and quotes embedded separators',()=>{const output=csv([['=HYPERLINK("bad")','texto;valor','áéí']]);assert.ok(output.startsWith('\ufeff'));assert.ok(output.includes("'=HYPERLINK"));assert.ok(output.includes('"texto;valor"'));});
test('invoice request from accepted quote preserves negotiated amounts and prevents duplicate conversion',()=>{let {data,b,id,w}=setup(),r=requestDocument(data,id,{type:'quote'},[w.id]),d=prepareDocument(data,r.id,{date:'2026-09-18',due:'2026-10-18'});assert.throws(()=>invoiceAcceptedQuote(data,d.id),/aceptación/);editQuote(data,d.id,{preparedBy:'Responsable',reviewer:'Administración',notes:'',due:d.due},[{...d.lines[0],price:200}]);quoteTransition(data,d.id,'review');quoteTransition(data,d.id,'approve');quoteTransition(data,d.id,'accept');let invoice=invoiceAcceptedQuote(data,d.id);assert.equal(invoice.lines[0].price,200);assert.equal(invoice.quote,d.id);assert.throws(()=>invoiceAcceptedQuote(data,d.id),/ya tiene/);});

test('saved customers and catalogue services reject duplicate identifiers',()=>{const {data}=setup();const c=saveCustomer(data,{name:'Cliente',taxId:'TEST-99',address:'Dirección'});assert.ok(c.id);assert.throws(()=>saveCustomer(data,{name:'Otro',taxId:'test-99',address:'Dirección'}),/Ya existe/);const p=saveProduct(data,{name:'Servicio',code:'SRV-1',price:100,tax:21});assert.equal(p.price,100);assert.throws(()=>saveProduct(data,{name:'Duplicado',code:'srv-1',price:1,tax:10}),/código/);});
test('discount and multiple IVA types reconcile to totals',()=>{const lines=[{qty:2,price:100,discount:10,tax:21},{qty:1,price:100,tax:10},{qty:1,price:50,tax:0,taxKind:'exempt'}];assert.deepEqual(amounts(lines),{base:330,tax:47.8,total:377.8});const groups=taxBreakdown(lines);assert.equal(groups.length,3);assert.equal(groups[2].label,'Exento');});
test('requests target company members and reject external identities',()=>{const {data,id,w}=setup();assert.throws(()=>requestDocument(data,id,{type:'quote',assignee:'outside'},[w.id]),/empresa/);const r=requestDocument(data,id,{type:'quote',assignee:'demo-admin'},[w.id]);assert.equal(r.assignee,'demo-admin');assert.equal(r.createdBy,'demo-owner');});
