import test from 'node:test';
import assert from 'node:assert/strict';
import {initial,counts} from '../model.js';
import {ensureFlows,saveFlow} from '../workflows.js';
import {ensureBilling,saveCustomer,addWork,requestDocument,prepareDocument,completeWork,addPayment,workStatus,makeDeliverable,quoteTransition} from '../billing-model.js';
function setup(){const data=initial(),b=ensureBilling(data),deal=data.deals[0].id;Object.assign(b.settings,{company:'Emisor',taxId:'EMISOR',address:'Dirección'});b.projects[deal].code='TEST';const a=saveCustomer(data,{name:'Empresa A',taxId:'A',address:'Dirección A'}),c=saveCustomer(data,{name:'Empresa B',taxId:'B',address:'Dirección B'});const work=customer=>addWork(data,deal,{label:'Certificación',entity:'Estructura 1',qty:1,price:100,tax:21,customerId:customer.id,managed:true,commercial:'agreement',agreement:'Contrato 2026'});return {data,b,deal,a,c,work};}
test('one project can contain multiple payers but each request and invoice has one frozen fiscal recipient',()=>{const {data,b,deal,a,c,work}=setup(),w1=work(a),w2=work(c);completeWork(data,deal,w1.id);completeWork(data,deal,w2.id);assert.throws(()=>requestDocument(data,deal,{type:'invoice'},[w1.id,w2.id]),/mismo cliente/);const r=requestDocument(data,deal,{type:'invoice'},[w1.id]);a.name='Modificado';const doc=prepareDocument(data,r.id,{date:'2026-09-18',due:'2026-10-18'});assert.equal(doc.customer.name,'Empresa A');assert.equal(requestDocument(data,deal,{type:'invoice'},[w2.id]).customer.name,'Empresa B');assert.equal(b.documents.length,1);});
test('managed work requires authorization and completion; motivated advances are explicit',()=>{const {data,deal,a,work}=setup(),w=work(a);assert.throws(()=>requestDocument(data,deal,{type:'invoice'},[w.id]),/ejecución/);assert.throws(()=>requestDocument(data,deal,{type:'invoice',advance:true},[w.id]),/motivo/);const r=requestDocument(data,deal,{type:'invoice',advance:true,note:'Cobro inicial pactado',paymentDays:60,paymentMethod:'Transferencia'},[w.id]);assert.equal(r.paymentDays,60);assert.equal(r.advance,true);});
test('quote acceptance authorizes managed work without inventing execution',()=>{const {data,deal,a,work}=setup(),w=work(a);w.commercial='quote';completeWork(data,deal,w.id);assert.throws(()=>requestDocument(data,deal,{type:'invoice'},[w.id]),/aceptación/);const r=requestDocument(data,deal,{type:'quote'},[w.id]),d=prepareDocument(data,r.id,{date:'2026-09-18',due:'2026-10-18'});quoteTransition(data,d.id,'review');quoteTransition(data,d.id,'approve');quoteTransition(data,d.id,'accept');assert.ok(requestDocument(data,deal,{type:'invoice'},[w.id]));});
test('grouped invoice payments allocate proportionally and reconcile at full payment',()=>{const {data,b,deal,a,work}=setup(),w1=work(a),w2=work(a);w2.price=200;completeWork(data,deal,w1.id);completeWork(data,deal,w2.id);const r=requestDocument(data,deal,{type:'invoice'},[w1.id,w2.id]),d=prepareDocument(data,r.id,{date:'2026-09-18',due:'2026-10-18'});addPayment(data,d.id,{amount:181.5,date:'2026-09-19'});assert.equal(workStatus(data,deal,w1).collected,60.5);assert.equal(workStatus(data,deal,w2).collected,121);assert.equal(workStatus(data,deal,w1).label,'Cobro parcial');addPayment(data,d.id,{amount:181.5,date:'2026-09-20'});assert.equal(workStatus(data,deal,w2).label,'Cobrado');});
test('each technical document is a reviewable snapshot tied to its structure and work',()=>{const {data,b,deal,a,work}=setup(),w=work(a);const doc=makeDeliverable(data,deal,w.id,'certificate');assert.ok(doc.body.includes('Estructura 1'));assert.ok(doc.body.includes('Empresa A'));assert.equal(doc.status,'draft');assert.notEqual(w.execution,'done');b.templates[0].body='Changed';assert.notEqual(doc.body,'Changed');assert.equal(doc.work,w.id);});
test('continuous projects stay open and stage reordering preserves project meanings',()=>{const data=initial(),flows=ensureFlows(data),d=data.deals[0];d.flowId='continuo';d.stage=1;assert.ok(counts(data).open>0);const f=flows.find(f=>f.id==='continuo');saveFlow(data,{id:f.id,name:f.name,stages:'En ejecución\nInicio',continuous:'on'});assert.equal(d.stage,0);assert.throws(()=>saveFlow(data,{id:f.id,name:f.name,stages:'Inicio'}),/contiene proyectos/);});
